# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df589593f76e49f7959948cf20bb7aa98ad68497c7cdcae83ef345ecef2f8f8a58f348c8f64285adec016b981ccb88b57eea90aaf70d7ea54c005203585dc0f3

test:
  secret_key_base: 1ff341d5e78cb1a1fb231def6ba85418fbbff2ed68e51868b116fba273d15ad9d6512b2da3da071731ad04346fee58562d476ccf41b95ca92dc7c4db726347f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
